### ISSUE TITLE
1.12 latest version crashing on startup

### ISSUE THREAD

**Issue by Zygus42** [DimensionalDevelopment/DimDoors#63] opened 2018-04-28 08:38 UTC
DimensionalDoors-3.0.8-271 is crashing on  startup.
Dimdoors-3.0.7-b-1.233 is NOT crashing on startup.
forge-1.12.2-14.23.3.2673-installer-win

It looks like some kind of conflict with the Perfect Spawn mod, so please let me know if I should report it there instead.

[crash-2018-04-28_16.28.58-server.txt](https://github.com/DimensionalDevelopment/DimDoors/files/1957481/crash-2018-04-28_16.28.58-server.txt)

**Comment by Robijnvogel** [comment] 2018-04-28 10:48
Duplicate of #58

**Closed by Robijnvogel** 2018-04-28 10:48 UTC
Labels: Duplicate
