### ISSUE TITLE
DimDoors loads every registered unloaded dimension when entering a rift

### ISSUE THREAD

**Issue by blairwilson** [DimensionalDevelopment/DimDoors#165] opened 2020-09-19 13:30 UTC
We unload unused worlds on our server to reduce lag.

When a player enters a DimDoor, the server goes through each of these unloaded worlds individually and loads them, presumably your code has some method to see if X dimensions are DimDoors dims or not.

Could you fix this?

**Comment by Erycus** [comment] 2020-10-05 17:30
Duplicate of https://github.com/DimensionalDevelopment/DimDoors/issues/86

Would really be nice if this got more attention though, as on multiplayer this causes timeout issues and then tps lag (along with the server being seemingly unstable afterwards and prone to crashing).

**Closed as completed** 2021-04-21 08:10 UTC
Labels: bug, duplicate, 1.12.2
