### ISSUE TITLE
Server kicking all players

### ISSUE THREAD

**Issue by omerbadawy11** [DimensionalDevelopment/DimDoors#149] opened 2020-05-28 09:29 UTC
It seems that when I go through a dim door the server goes into a frenzy of loading every single dimension then unloading it
I confirmed that it's DimDoors fault since all other portals and dimension teleportation works fine, except DimDoors.

https://gist.github.com/omerbadawy11/ebe212afd5b3a7641ea02c2095c455a1

Any help is greatly appreciated!

**Comment by CreepyCre** [comment] 2021-04-21 08:17
Duplicate of #86

**Closed as completed by CreepyCre** 2021-04-21 08:17 UTC
Labels: bug, duplicate, 1.12.2
