### ISSUE TITLE
DimDoors Causing issues with Mo Creature Entity Ticking

### ISSUE THREAD

**Issue by schiegirl** [DimensionalDevelopment/DimDoors#111] opened 2019-04-17 02:54 UTC
Issue: Client Crash upon loading, via an entity ticking error with a Mo Creatures Mob

Expected Behavior: The client loads the game and doesn't crash

Steps to Reproduce: Unknown, I'm guessing it has to do with rifts and entities spawning, we have had issues in the past but nothing to this extent.

Problem Continued Below

Had a server crippling problem today, where Mo Creatures underwater entities were crashing clients on load. Killing the entity in question via cofh killall console commands would work for a few seconds but the problem would immediately return with another underwater entity causing it. Then I found this: https://www.mocreatures.org/mobile/forum/viewthread/m/13290502/id/31466985-odd-ticking-entity-error-mocreatures

So after trying to disable the mobs in question, killing them, restarting the server, unloading chunks, going to backups from the previous day, removing newer mods that had been added in the last 24 hours and reinstalling minecraft from scratch. I finally removed DimDoors and sure enough, the problem vanished.

Attached are the last 5 crash reports, out of 60, they're all about the same, if you'd like to see more, I can definitely provide them. Would really like to see this somehow fixed because I love both MoCreatures and Dim Doors and I really want to see what Dim Doors has to offer in the future. If you need any additional information please let me know.

[crash-2019-04-16_22.02.55-client.txt](https://github.com/DimensionalDevelopment/DimDoors/files/3087696/crash-2019-04-16_22.02.55-client.txt)
[crash-2019-04-16_22.01.59-client.txt](https://github.com/DimensionalDevelopment/DimDoors/files/3087697/crash-2019-04-16_22.01.59-client.txt)
[crash-2019-04-16_22.00.49-client.txt](https://github.com/DimensionalDevelopment/DimDoors/files/3087698/crash-2019-04-16_22.00.49-client.txt)
[crash-2019-04-16_21.48.17-client.txt](https://github.com/DimensionalDevelopment/DimDoors/files/3087699/crash-2019-04-16_21.48.17-client.txt)
[crash-2019-04-16_21.48.04-client.txt](https://github.com/DimensionalDevelopment/DimDoors/files/3087700/crash-2019-04-16_21.48.04-client.txt)

**Comment by Robijnvogel** [comment] 2019-04-18 19:07
Duplicate of #21 
Your version of Dimdoors is very outdated. This issue is supposed to be fixed in the latest release.
If you still have this issue with the latest version, please let us know.

**Closed by Robijnvogel** 2019-04-18 19:07 UTC

**Comment by schiegirl** [comment] 2019-04-18 19:58
Where's a newer version? The newest version on Curseforge is 3.0.9-287 which is the version we were running.
