### ISSUE TITLE
Personal pocket keeps getting wiped

### ISSUE THREAD

**Issue by CosmicGlowsticks** [DimensionalDevelopment/DimDoors#109] opened 2019-03-23 22:35 UTC
It keeps getting wiped, it's awful. I worked for hours last night and it was gone this morning.

**Comment by CosmicGlowsticks** [comment] 2019-03-25 22:20
Ack, I thought I posted the logs. How would it get disconnected in the first place?

**Comment by Runemoro** [comment] 2019-03-26 13:52
We can't know without the logs. Do you still have them? This is the first time this was reported on the latest version, it may be an incompatibility with some other mod. (If you're using an older version, though, update to the latest one as we've fixed a few things)

**Comment by CosmicGlowsticks** [comment] 2019-03-26 19:59
[2019-03-22-7.log.gz](https://github.com/DimensionalDevelopment/DimDoors/files/3010078/2019-03-22-7.log.gz)
[2019-03-23-1.log.gz](https://github.com/DimensionalDevelopment/DimDoors/files/3010079/2019-03-23-1.log.gz)


[2019-03-23-2.log.gz](https://github.com/DimensionalDevelopment/DimDoors/files/3010082/2019-03-23-2.log.gz)
Not sure which one I should add but here. I am indeed using the latest version, the one from May last year

**Comment by Runemoro** [comment] 2019-03-27 01:22
It seems to be an incompatibility with Gravestone Extended.

https://paste.dimdev.org/wagedogozo.txt

**Comment by CosmicGlowsticks** [comment] 2019-03-27 01:49
How would that impact my personal pocket?? At all??

**Comment by Runemoro** [comment] 2019-03-27 01:51
Something from that mod generated over a rift during worldgen, and broke the rift registry somehow.

**Comment by CosmicGlowsticks** [comment] 2019-03-27 02:10
That is.. weird and I'm not sure how that would happen.

**Comment by Robijnvogel** [comment] 2020-03-22 12:03
Duplicate of #85

**Closed** 2021-04-21 08:38 UTC
Labels: 1.12.2, Bug, Duplicate
