### ISSUE TITLE
Dimension Reset

### ISSUE THREAD

**Issue by DeHaynes** [DimensionalDevelopment/DimDoors#114] opened 2019-05-08 17:38 UTC
Pocket Dimension reset.

In my modpack, I planned on using a pocket dimension as a travel hub with doors around it that lead to various other areas.  Last night I set up the first two areas.  It worked fine until I rebooted the server.  I was able to setup the doors and had someone else traverse them successfully.

After the reboot, the pocket dimension was like it was brand new.  

I read other open issues where this happened and I scanned my log file.  I see an dimdoor entry complaining about storage but then I am lost. 

[2019-05-07-3.log.gz](https://github.com/DimensionalDevelopment/DimDoors/files/3158659/2019-05-07-3.log.gz)

**Comment by madokaorimura** [comment] 2019-07-18 02:48
Uncompress the file then upload it to gist.github.com
I can't do it on my phone

**Comment by Nocturne705** [comment] 2019-09-04 05:54
This also happened to me. It occurs on every reset.

The dimension is not wiped, a new pocket is simply generated. The previous pocket is still present, but unreachable. By going into admin mode and using a minimap mod you can fly under the world and locate the previous dimension.

This is fortunate because I tried to move my entire Thaumcraft setup into a personal pocket only to think I had lost literally hours worth of stuff.

**Comment by CodingEagle02** [comment] 2019-09-18 18:23
I think I have the same issue.

After playing around with them, I discovered if I quit the world and reload, the dimension is "wiped". But after experimenting, I discovered if I link a door inside the first pocket to a door in the overworld, when the quartz door is reset, I can still go to the first pocket through the linked door. In fact, I went as far as to make rifts directly linking both pockets just to prove that I did, indeed, have two personal pockets.

**Comment by Waterpicker** [comment] 2019-10-08 08:02
Yea. The dimensions holding pocket dimensions are void worlds with every pockets being extremely far apart. The personal pockets are suppose to be per player but an issue with the system causes personal pocket attached to the player to reset.

**Comment by GrantGryczan** [comment] 2019-10-11 18:47
I have the same issue. This is a pretty significant problem. When might it be fixed?

**Comment by Robijnvogel** [comment] 2020-03-22 12:04
Duplicate of #85

**Closed** 2021-04-21 08:36 UTC
Labels: 1.12.2, Bug, Duplicate
