### ISSUE TITLE
1.17 - bug with generating of structure

### ISSUE THREAD

**Issue by IAEGOR** [DimensionalDevelopment/DimDoors#215] opened 2021-07-04 11:35 UTC
This mod will interfere with structure generation,
villages, mineshafts and strongholds not spawn, some modded structures may also not spawn.

**Comment by CreepyCre** [comment] 2021-07-04 11:49
Duplicate of #214.
Has also already been fixed.

**Closed as completed by CreepyCre** 2021-07-04 11:49 UTC
Labels: duplicate
