### ISSUE TITLE
Crash on Startup [3 Beta 5.1]

### ISSUE THREAD

**Issue by Nargath** [DimensionalDevelopment/DimDoors#37] opened 2018-01-19 11:25 UTC
MC: 1.12.2
Forge: 14.23.1.2586
Dimension Doors: 3 Beta 5.1

Added the new version to my mods folder, launched the game and then got the crash below:
https://gist.github.com/Nargath/8b84f3ff20669af8498c5122278dcaae

**Comment by Robijnvogel** [comment] 2018-01-19 11:27
Duplicate of #36

**Closed by Robijnvogel** 2018-01-19 11:27 UTC
Labels: Duplicate

**Comment by Robijnvogel** [comment] 2018-01-19 11:28
By the way, disable FoamFix' Fast Hopper in its config file as a patch for now. :)
