### ISSUE TITLE
Crash when loading with RFTools Dimensions in the pack.

### ISSUE THREAD

**Issue by djnifos** [DimensionalDevelopment/DimDoors#22] opened 2018-01-07 21:14 UTC
[https://pastebin.com/Yvn1xU7j](https://pastebin.com/Yvn1xU7j)

RFTools Dimensions threw the crash, but the pack loaded fine until I added Dimensional Doors.  Cross posted to both gits.

**Comment by josephcsible** [comment] 2018-01-07 21:15
Duplicate of #20. The build linked there will fix it, so just use it until the next official release.

**Comment by Runemoro** [comment] 2018-01-07 21:15
This was already fixed for the next beta. Use https://github.com/DimensionalDevelopment/DimDoors/issues/20 for now.

**Closed by Runemoro** 2018-01-07 21:15 UTC

**Comment by Robijnvogel** [comment] 2018-01-07 21:33
@djnifos to prevent posting a duplicate issue in the future, search the issues first and remove the ` is:open` tag from the search. :)
https://github.com/DimensionalDevelopment/DimDoors/issues?q=is%3Aissue+rftools

**Comment by djnifos** [comment] 2018-01-08 12:33
Will do, thank you
