### ISSUE TITLE
Personal dimension not being found after server restart, resulting in a new one being generated

### ISSUE THREAD

**Issue by jtljac** [DimensionalDevelopment/DimDoors#135] opened 2020-02-14 23:14 UTC
Whole File (could not upload the whole file in pastebin as its too long): [latest.log](https://github.com/DimensionalDevelopment/DimDoors/files/4207268/latest.log)
Specific error in console: https://pastebin.com/g7qZaJHs
this error appears to happen when they enter the door

**Comment by Robijnvogel** [comment] 2020-03-22 12:05
Duplicate of #85

**Closed** 2021-04-21 08:23 UTC
Labels: 1.12.2, Bug, Duplicate
