### ISSUE TITLE
Quartz door keeps changing!

### ISSUE THREAD

**Issue by vevlaa** [DimensionalDevelopment/DimDoors#144] opened 2020-05-11 04:40 UTC
So, I'm playing on a 1.3.5.3 MC Eternal server.
I've wanted to build a reactor in a private pocket dimension, and a friend of mine has already done this on the same server. (note he has not had this issue on the server.)

So I made a quartz door, entered it, made a gold door on the inside, and replaced in the floor.

After the server restarted, when I tried to enter the door, it would spawn a new room for me.
This time I wanted to make sure that I would have access if anything like this happened again, so I set up a EnderIO teleport pad to get me there if the doors were to fail me again.

Queue the next restart. Door changed again. I had dropped down a way point in there so I could see I was about 1k blocks away from the original location. Tried the pad, and that got me onto the "old" one, so at least I have access to it. The golden door is still there, and connects to the overworld just fine. Entering the overworld door sends me straight back to the "new" location again though.

Now not sure about how much you know about EnderIO teleporters, but they are quite expensive in resources to use, and really not worth the resources to use this much.

I tried entering the "new" one, break the door, and removed the rift. Went back (Server has /home enabled) Door in the overword and tried again. This made another new location...

Then I removed that door and rift. Went back and used the teleporter to get back in to the correct one, and went back through that door. Works fine. Goes back in, and, you guessed it, new room!

Does anyone know of a good fix/help to this?

**Comment by Robijnvogel** [comment] 2020-05-11 17:34
Duplicate of #85

**Comment by vevlaa** [comment] 2020-05-12 00:17
> Duplicate of #85

Yes... that is very helpful, thanks...
How about a solution instead. as #85 is NOT helpful at all.

**Comment by theishiopian** [comment] 2020-05-12 01:16
Yes it is. #85 was closed, which means this issue was fixed in a later version.

**Comment by vevlaa** [comment] 2020-05-12 08:41
First off, Sorry for being rude. That was uncalled for. I had a bad day when I wrote my last comment.

> Yes it is. #85 was closed, which means this issue was fixed in a later version.
 
Looking at #85 now, This has the "Open status" "Bug" tag and a single comment? Am I missing something? Or are you referring to #64 ? 
MC Eternal is running Dimensional Doors version 3.0.9 Not sure what the current build is?

**Comment by Robijnvogel** [comment] 2020-05-12 16:24
@vevlaa I am just trying to link all related issues to one, so we can more easily access all the reports and information we have on this bug at a later point in time when we have the time to take a good look at it.

If it would be completely up to me, there will be no further full release before this issue is resolved, but I realize that that statement is pretty much void because of the overall lack of releases lately. ;)

**Closed as completed** 2021-04-21 08:21 UTC
Labels: bug, duplicate, 1.12.2
